pid:
    surge:
        kp: 50.0
        ki: 0.0
        kd: 0.0
        clamp: 0.4
        angular: false

    sway:
        kp: 50.0
        ki: 0.0
        kd: 0.0
        clamp: 0.4
        angular: false

    heave:
        kp: 50.0
        ki: 12.0
        kd: 0.0
        clamp: 0.43
        angular: false

    pitch:
        kp: 50.0
        ki: 0.0
        kd: 0.0
        clamp: 0.4
        angular: true

    yaw:
        kp: 50.0
        ki: 0.0
        kd: 0.0
        clamp: 0.4
        angular: true
